inputs: assets/computational
outputs: outputs/computational
tasks:
  layout_detection:
    model: layout_detection_layoutlmv3
    model_config:
      model_path: models/Layout/LayoutLMv3/model_final.pth
      visualize: True